/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import model.dao.LoginInfoDAO;
import model.to.LoginInfoTO;

public class ViewLoginInfo extends javax.swing.JInternalFrame {
 ArrayList<LoginInfoTO> allLoginData;
 JPopupMenu jpopup;
 int row;
    
    public ViewLoginInfo() {
        initComponents();
        setSize(650,450);
        row=-1;
        bindTableData();
        jpopup=new JPopupMenu();
        JMenuItem jmiUpdate=new JMenuItem("Update This Record");
        jpopup.add(jmiUpdate);
        JMenuItem jmiDelete=new JMenuItem("Delete This Record");
        jpopup.add(jmiDelete);
        jmiDelete.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                deleteRecord(); 
            }
        });
        jmiUpdate.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                updateRecord(); 
            }
        });
    }
    private void deleteRecord(){
        if(row!=-1){
            LoginInfoTO cit=allLoginData.get(row);
            if(cit!=null){
                int result=JOptionPane.showConfirmDialog(this,"Are You Sure You Want To Delete This Record?",
                        "Message From Admin",JOptionPane.OK_CANCEL_OPTION);
                if(result==JOptionPane.OK_OPTION){
                    LoginInfoDAO action=new LoginInfoDAO();
                    if(action.deleteRecord(cit.getUserName())){
                      JOptionPane.showMessageDialog(this,"Record is Deleted");
                      bindTableData();
                      row=-1;
                    }else{
                        JOptionPane.showMessageDialog(this,action.getErrorMessage());
                    }
                }
            }
        }
    }
      private void updateRecord(){
        if(row!=-1){
            LoginInfoTO cit=allLoginData.get(row);
            if(cit!=null){
                AddLoginInfo obj=new AddLoginInfo(cit);
                obj.setVisible(true);
                obj.setTitle("Update Login info");
                JDesktopPane jdp=getDesktopPane();
                jdp.add(obj);
                try{
                    obj.setSelected(true);
                }catch(PropertyVetoException ex){
                    
                }
               dispose();               
            }
        }
    }
private void bindTableData(){
    allLoginData=new LoginInfoDAO().getAllRecords();
    if(allLoginData!=null && allLoginData.size()!=0){
        int totalRows=allLoginData.size();
        String[] columnNames={"UserName" ,"Password"};
        Object allData[] []=new Object[totalRows] [columnNames.length];
        for(int i=0;i<totalRows;i++){
            LoginInfoTO cit=allLoginData.get(i);
            allData[i]=new Object[columnNames.length];
            allData[i][0]=cit.getUserName();
            allData[i][1]=cit.getPassword();
        }
        DefaultTableModel dtm=new DefaultTableModel(allData,columnNames);
        jtViewLoginInfo.setModel(dtm);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtViewLoginInfo = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("View LoginInfo");

        jtViewLoginInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtViewLoginInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtViewLoginInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtViewLoginInfo);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtViewLoginInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtViewLoginInfoMouseClicked
       if(evt.getButton()==MouseEvent.BUTTON3){
           int idx=jtViewLoginInfo.rowAtPoint(evt.getPoint());
           jtViewLoginInfo.getSelectionModel().setSelectionInterval(idx, idx);
           row=jtViewLoginInfo.getSelectedRow();
           System.out.println(row);
           jpopup.show(jtViewLoginInfo,evt.getX(),evt.getY());
       }
    }//GEN-LAST:event_jtViewLoginInfoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtViewLoginInfo;
    // End of variables declaration//GEN-END:variables
}
